language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
env:
  - PYTEST=2.0.3
  - PYTEST=2.1.3
  - PYTEST=2.2.4
  - PYTEST=2.3.5
  - PYTEST=2.4.2
  - PYTEST=2.5.2
  - PYTEST=2.6.4
  - PYTEST=2.7.0
install:
  - pip install -q pytest==$PYTEST
  - pip install -q -e .
script:
  - py.test
